version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - '27019:27017'
    volumes:
      - './data-db:/data/db'

volumes:
  mongodata:
    driver: local
